call ..\git-create-filtered-repo.bat C:\_iPL\iPodLinux armemu "tools/armemu apps/desktop/armemu"
call ..\git-create-filtered-repo.bat C:\_iPL\iPodLinux bots "apps/desktop/bots management/*.pl maintenance/*.pl"
call ..\git-create-filtered-repo.bat C:\_iPL\iPodLinux installer2 "apps/desktop/installer2 tools/installer"
call ..\git-create-filtered-repo.bat C:\_iPL\iPodLinux iplsign "apps/desktop/iplsign tools/iplsign tools/iplsign.c"
call ..\git-create-filtered-repo.bat C:\_iPL\iPodLinux pzconf "apps/desktop/pzconf tools/pzconf"
call ..\git-create-filtered-repo.bat C:\_iPL\iPodLinux cmdlineutils "apps/ipod/cmdlineutils tools/cmdlineutils"
call ..\git-create-filtered-repo.bat C:\_iPL\iPodLinux getflash "apps/ipod/getflash tools/getflash"
call ..\git-create-filtered-repo.bat C:\_iPL\iPodLinux ipodinfo "apps/ipod/ipodinfo tools/ipodinfo"
call ..\git-create-filtered-repo.bat C:\_iPL\iPodLinux ipodloader2 "apps/ipod/ipodloader2 tools/ipodloader2"
call ..\git-create-filtered-repo.bat C:\_iPL\iPodLinux podzilla2 "apps/ipod/podzilla2 tools/podzilla2"
call ..\git-create-filtered-repo.bat C:\_iPL\iPodLinux 2bppconv "legacy/2bppconv trunk/tools/video/2bppconv"
call ..\git-create-filtered-repo.bat C:\_iPL\iPodLinux inputattach "legacy/inputattach trunk/tools/inputattach"
call ..\git-create-filtered-repo.bat C:\_iPL\iPodLinux ipodeth1394 "legacy/ipodeth1394 trunk/tools/ipodeth1394"
call ..\git-create-filtered-repo.bat C:\_iPL\iPodLinux ipodloader "legacy/ipodloader trunk/tools/ipodloader"
call ..\git-create-filtered-repo.bat C:\_iPL\iPodLinux nano-x "legacy/nano-x trunk/tools/microwindows"
call ..\git-create-filtered-repo.bat C:\_iPL\iPodLinux patch_fw "legacy/patch_fw trunk/tools/patch_fw"
call ..\git-create-filtered-repo.bat C:\_iPL\iPodLinux podfile "legacy/podfile tools/podfile"
call ..\git-create-filtered-repo.bat C:\_iPL\iPodLinux podzilla "legacy/podzilla trunk/tools/podzilla"
call ..\git-create-filtered-repo.bat C:\_iPL\iPodLinux ttkzilla "legacy/ttkzilla tools/ttkzilla"
call ..\git-create-filtered-repo.bat C:\_iPL\iPodLinux hotdog "libs/hotdog tools/hotdog"
call ..\git-create-filtered-repo.bat C:\_iPL\iPodLinux libipod "libs/libipod tools/libipod"
call ..\git-create-filtered-repo.bat C:\_iPL\iPodLinux rawpod "libs/rawpod tools/rawpod"
call ..\git-create-filtered-repo.bat C:\_iPL\iPodLinux SDL "libs/SDL tools/SDL"
call ..\git-create-filtered-repo.bat C:\_iPL\iPodLinux ttk "libs/ttk tools/ttk"
call ..\git-create-filtered-repo.bat C:\_iPL\iPodLinux ucdl "libs/ucdl tools/ucdl"
call ..\git-create-filtered-repo.bat C:\_iPL\iPodLinux linux "linux trunk/linux trunk/linux-2.6"
call ..\git-create-filtered-repo.bat C:\_iPL\iPodLinux uclibc "uclibc trunk/uClinux-dist"
call ..\git-create-filtered-repo.bat C:\_iPL\iPodLinux website "trunk/website"